# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20180814_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
