# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20180817_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
