# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_tipopago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='Documento',
            new_name='CUIT',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Direccion',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
