# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_venta'),
        ('compras', '0006_auto_20180820_2343'),
    ]

    operations = [
    ]
