# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_merge_20180822_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta',
            new_name='Compra',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='idVenta',
            new_name='idCompra',
        ),
    ]
