# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20180824_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcompra',
            name='Compras',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelcompra',
            name='Costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='modelcompra',
            name='CostoUnidades',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelcompra',
            name='ExistenciaFinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelcompra',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
