# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20180903_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Detalle',
        ),
        migrations.AlterField(
            model_name='producto',
            name='Cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
